// components/Footer.vue
<template>
  <footer class="c-footer">
    <hr class="o-divider" />
    <div class="o-container">
      <nuxt-picture
        class="c-footer__logo"
        :src="`/images/${attributes.logo.default}`"
        :srcset="`/images/${attributes.logo.twoTimes} 2x`"
        :alt="attributes.logo.alt"
        format="webp"
        loading="lazy"
      />

      <nav class="c-footer__items">
        <nuxt-link
          v-for="(item, index) in attributes.menuItems"
          :key="index"
          class="c-footer__link"
          :to="item.url"
        >
          {{ item.name }}
        </nuxt-link>
      </nav>

      <small class="c-footer__copyright">
        2020 Valtech All rights reserved
      </small>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer',

  data() {
    return {
      attributes: {
        menuItems: [
          {
            name: 'Home',
            url: '/',
          },
          {
            name: 'The Show',
            url: '/the-show',
          },
          {
            name: 'Episodes',
            url: '/episodes',
          },
          {
            name: 'Contact',
            url: '/contact',
          },
        ],
        logo: {
          default: 'logo-valtech-footer.png',
          twoTimes: 'logo-valtech-footer@2x.png',
          alt: 'Valtech logo',
        },
      },
    }
  },
}
</script>

// src/components/Footer/index.tsx
import React from 'react';
import { Link } from 'react-router-dom';

import logoWhite from '../../assets/logo-white.svg';

import { Container, Links } from './styles';

const Footer: React.FC = () => {
  return (
    <Container>
      <div className="logo-img">
        <img src={logoWhite} alt="valtech" />
      </div>

      <Links>
        <li>
          <Link to="/">Home</Link>
        </li>
        <li>
          <Link to="/">The show</Link>
        </li>
        <li>
          <Link to="/">Episodes</Link>
        </li>
        <li>
          <Link to="/">Contact</Link>
        </li>
      </Links>

      <p className="copyright">2020 Valtech All rights reserved</p>
    </Container>
  );
};

export default Footer;
